---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Because I feel that, in the Heavens above, The angels, whispering to one another,

Can find, among their burning terms of love, None so devotional as that of “Mother,”

Therefore by that dear name I long have called you— You who are more than mother unto me,

And fill my heart of hearts, where Death installed you In setting my Virginia’s spirit free. My mother—my own mother, who died early,

Was but the mother of myself; but you Are mother to the one I loved so dearly,

And thus are dearer than the mother I knew By that infinity with which my wife

Was dearer to my soul than its soul-life.
